# Generated by Django 5.1.1 on 2024-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachRate', '0002_teacher_designation_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_pictures/'),
        ),
    ]
