# Generated by Django 5.1.1 on 2024-12-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachRate', '0004_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')]),
        ),
    ]
